# Generated by Django 6.0.2 on 2026-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_hobby_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='port_image',
            field=models.CharField(default='https://img.freepik.com/free-vector/speech-bubble-with-interrogation-sign-cloud-isolated-icon_18591-83281.jpg?semt=ais_user_personalization&w=740&q=80', max_length=500),
        ),
    ]
